using System;
using VideoOS.Platform.DriverFramework.Definitions;

namespace MIP2VPS
{
    public static class Constants
    {
        public static readonly ProductDefinition Product1 = new ProductDefinition
        {
            Id = new Guid("08c6f81e-836e-47f9-81dc-b432a98d31d8"),
            Name = "My MIP2VPS"
        };

        public static readonly Guid DriverId = new Guid("d812253c-c9cb-438f-b3f8-ba0b1936e8ef");

        public static readonly Guid Audio1 = new Guid("27cf22d1-567c-46ca-aa4e-e74b6d5abae0");
        public static readonly Guid Video1 = new Guid("2371b335-d010-41a5-b8a9-7de97cc80a13");
        public static readonly Guid Input1 = new Guid("3563e885-fa5d-4ee0-ab70-16ce17fe7319");
        public static readonly Guid Metadata1 = new Guid("dd3dcd87-2258-467f-a4e5-c28668a5186e");
        public static readonly Guid Metadata2 = new Guid();
        public static readonly Guid Metadata3 = new Guid();
        public static readonly Guid Metadata4 = new Guid();
        public static readonly Guid Output1 = new Guid("0216399f-4e2c-4700-9669-017418305f6b");
        public static readonly Guid Speaker1 = new Guid("5ec878a6-061f-49ef-80b1-5eca526f3538");

        public static readonly Guid VideoStream1RefId = new Guid("e583c192-3208-4dbc-801e-b547f958ba33");
        public static readonly Guid AudioStream1RefId = new Guid("b5b6fcd5-488d-40b8-9531-d569c6ee5789");
        public static readonly Guid SpeakerStream1RefId = new Guid("AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA"); // TODO: Due to shortcoming in Visual Studio only up to 10 GUIDs can be auto-generated by template. Please replace this one with a newly generated unique ID.
    }
}
